name: CI + Docker Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Show Files
        run: ls -l

      - name: Build Docker Image
        run: docker build -t myapp:latest .

      - name: List Docker Images
        run: docker images
  
     - name: Run Container
       run: |
          docker run -d -p 8080:80 --name testcontainer myapp:latest
          sleep 5
          curl http://localhost:8080
